# .github/workflows/namespace-check.yml

name: "Namespace Check"
on:
  push:
    branches-ignore:
      - prod

jobs:
  namespace-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build component library in dist/
        run: yarn build

      - name: Namespace Checking
        run: yarn namespace-check
